# HUMAN ACTIVITY RECOGNITION

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv('C:/Users/rithu/Downloads/train.csv')

In [5]:
df.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [6]:
df.columns

Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X',
       ...
       'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)',
       'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'subject', 'Activity'],
      dtype='object', length=563)

In [7]:
df.shape

(7352, 563)

In [8]:
df.info

<bound method DataFrame.info of       tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245     

# making x and y

In [9]:
X=df.drop(['Activity'],axis=1)

In [10]:
y=df['Activity']

In [11]:
X.isnull()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0                 False              False              False   
1                 False              False              False   
2                 False              False              False   
3                 False              False              False   
4                 False              False              False   
...                 ...                ...                ...   
7347              False              False              False   
7348              False              False              False   
7349              False              False              False   
7350              False              False              False   
7351              False              False              False   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0                False             False             False             False   
1                False             False             False             False   
2                False             False             False             False   
3                False             False             False             False   
4                False             False             False             False   
...                ...               ...               ...               ...   
7347             False             False             False             False   
7348             False             False             False             False   
7349             False             False             False             False   
7350             False             False             False             False   
7351             False             False             False             False   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0                False             False             False  ...   
1                False             False             False  ...   
2                False             False             False  ...   
3                False             False             False  ...   
4                False             False             False  ...   
...                ...               ...               ...  ...   
7347             False             False             False  ...   
7348             False             False             False  ...   
7349             False             False             False  ...   
7350             False             False             False  ...   
7351             False             False             False  ...   

      fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                               False                            False   
1                               False                            False   
2                               False                            False   
3                               False                            False   
4                               False                            False   
...                               ...                              ...   
7347                            False                            False   
7348                            False                            False   
7349                            False                            False   
7350                            False                            False   
7351                            False                            False   

      angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                           False                                 False   
1                           False                                 False   
2                           False                                 False   
3                           False                                 False   
4                           False                                 False   
...                           ...                                   ...   
7347                        False            

In [12]:
y.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
7347    False
7348    False
7349    False
7350    False
7351    False
Name: Activity, Length: 7352, dtype: bool

In [13]:
X.dtypes

tBodyAcc-mean()-X                       float64
tBodyAcc-mean()-Y                       float64
tBodyAcc-mean()-Z                       float64
tBodyAcc-std()-X                        float64
tBodyAcc-std()-Y                        float64
                                         ...   
angle(tBodyGyroJerkMean,gravityMean)    float64
angle(X,gravityMean)                    float64
angle(Y,gravityMean)                    float64
angle(Z,gravityMean)                    float64
subject                                   int64
Length: 562, dtype: object

# pre processing and splitting 

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [16]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# modelling

In [17]:
from sklearn.svm import SVC


In [18]:
svm = SVC(kernel="linear")
svm.fit(X_train_scaled, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
svm.score(X_test_scaled,y_test)

0.9836779107725789

# predicting for new data set

In [20]:
new=pd.read_csv('C:/Users/rithu/Downloads/test.csv')

In [21]:
new.shape

(2947, 563)

In [22]:
new.info

<bound method DataFrame.info of       tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.257178          -0.023285          -0.014654   
1              0.286027          -0.013163          -0.119083   
2              0.275485          -0.026050          -0.118152   
3              0.270298          -0.032614          -0.117520   
4              0.274833          -0.027848          -0.129527   
...                 ...                ...                ...   
2942           0.310155          -0.053391          -0.099109   
2943           0.363385          -0.039214          -0.105915   
2944           0.349966           0.030077          -0.115788   
2945           0.237594           0.018467          -0.096499   
2946           0.153627          -0.018437          -0.137018   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.938404         -0.920091         -0.667683         -0.952501   
1            -0.975415     

In [23]:
X_new=new.drop(["Activity"],axis=1)

In [24]:
y_new=new["Activity"]

In [25]:
new_scaled=scaler.transform(X_new)

In [26]:
new_pred= svm.predict(new_scaled)

In [27]:
new_pred

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

# confusion matrix 

In [28]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(new_pred, y_new))
print(classification_report(new_pred, y_new))

[[537   0   0   0   0   0]
 [  0 416  19   0   0   0]
 [  0  74 513   0   0   0]
 [  0   0   0 493  12  17]
 [  0   0   0   3 386   0]
 [  0   1   0   0  22 454]]
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.85      0.96      0.90       435
          STANDING       0.96      0.87      0.92       587
           WALKING       0.99      0.94      0.97       522
WALKING_DOWNSTAIRS       0.92      0.99      0.95       389
  WALKING_UPSTAIRS       0.96      0.95      0.96       477

          accuracy                           0.95      2947
         macro avg       0.95      0.95      0.95      2947
      weighted avg       0.95      0.95      0.95      2947



# evaluating your model 

In [29]:
from sklearn import metrics
metrics.accuracy_score(new_pred,y_new)

0.9497794367153037

# Model 2

In [51]:
from sklearn import neighbors
KNN_model=neighbors.KNeighborsClassifier(n_neighbors=5,n_jobs=-1)
KNN_model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')

In [52]:
KNN_model.score(X_test,y_test)

0.9678998911860718

In [53]:
y_pred=KNN_model.predict(X_new)

In [54]:
y_pred

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING'], dtype=object)

# Evaluating

In [55]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_pred, y_new))
print(classification_report(y_pred, y_new))

[[509   0   0   0   0   0]
 [ 21 336  61   0   0   0]
 [  7 153 470   0   0   0]
 [  0   0   1 423  75 103]
 [  0   0   0  36 314  28]
 [  0   2   0  37  31 340]]
                    precision    recall  f1-score   support

            LAYING       0.95      1.00      0.97       509
           SITTING       0.68      0.80      0.74       418
          STANDING       0.88      0.75      0.81       630
           WALKING       0.85      0.70      0.77       602
WALKING_DOWNSTAIRS       0.75      0.83      0.79       378
  WALKING_UPSTAIRS       0.72      0.83      0.77       410

          accuracy                           0.81      2947
         macro avg       0.81      0.82      0.81      2947
      weighted avg       0.82      0.81      0.81      2947



In [56]:
from sklearn import metrics
metrics.accuracy_score(y_pred,y_new)

0.8116728876823889

# Model 3

In [57]:
from sklearn.tree import DecisionTreeClassifier

In [58]:
model=DecisionTreeClassifier()

In [59]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [60]:
model.score(X_test,y_test)

0.9325353645266594

In [63]:
pred=model.predict(X_new)

In [64]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(pred, y_new))
print(classification_report(pred, y_new))

[[537   0   0   0   0   0]
 [  0 382  89   0   0   0]
 [  0 109 443   0   0   0]
 [  0   0   0 471  27  60]
 [  0   0   0  18 320  31]
 [  0   0   0   7  73 380]]
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.78      0.81      0.79       471
          STANDING       0.83      0.80      0.82       552
           WALKING       0.95      0.84      0.89       558
WALKING_DOWNSTAIRS       0.76      0.87      0.81       369
  WALKING_UPSTAIRS       0.81      0.83      0.82       460

          accuracy                           0.86      2947
         macro avg       0.85      0.86      0.86      2947
      weighted avg       0.86      0.86      0.86      2947



In [65]:
from sklearn import metrics
metrics.accuracy_score(pred,y_new)

0.8595181540549711

# Model4

In [66]:
from sklearn.linear_model import LogisticRegression

In [68]:
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

C:\Users\rithu\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\rithu\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
LogReg.score(X_test,y_test)

0.9863982589771491

In [73]:
y_pred1 = LogReg.predict(X_new)

In [74]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_pred1, y_new)
confusion_matrix


array([[537,   0,   0,   0,   0,   0],
       [  0, 434,  13,   0,   0,   0],
       [  0,  54, 517,   0,   0,   0],
       [  0,   0,   2, 494,   5,  22],
       [  0,   0,   0,   2, 406,   0],
       [  0,   3,   0,   0,   9, 449]], dtype=int64)

In [76]:
print(classification_report(y_pred1, y_new))

                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.88      0.97      0.93       447
          STANDING       0.97      0.91      0.94       571
           WALKING       1.00      0.94      0.97       523
WALKING_DOWNSTAIRS       0.97      1.00      0.98       408
  WALKING_UPSTAIRS       0.95      0.97      0.96       461

          accuracy                           0.96      2947
         macro avg       0.96      0.96      0.96      2947
      weighted avg       0.96      0.96      0.96      2947



In [77]:
from sklearn import metrics
metrics.accuracy_score(y_pred1,y_new)

0.9626739056667798